version: '3.1'

services:

  
  githubaction:
    build: .
    container_name: githubaction
    ports:
      - 8080:8080
  
  newman:
    build: ./NewmanCli
    image: newman
    container_name: newman
    entrypoint: ["/home/hello_django/entrypoint.sh"]
    
  
   
