version: '3.1'

services:

  
  githubaction:
    build: .
    container_name: githubaction
    ports:
      - 80:80
      - 443:443
    
  
  newman:
    build: ./NewmanCli
    image: newman
    entrypoint: ["/home/hello_django/entrypoint.sh"]
    container_name: newman
    
  
   
