name: Test

on:
  push:
    branches:
      - master
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npm package
        run: npm init npm install
      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.3.6
        with:
          build: npm run build
          start: npm start
      - name: Jest run
        run: npm test
