name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Build and Test with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
  

  build-docker-image:
    name: Build Docker image
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: docker-compose build
      - name: Run the docker-compose stack
        run: docker-compose up -d
      - name: Check container is live
        run: docker ps
      - name: Show Newman results
        run: |
          sleep 10s
          docker logs newman
      - name: Check Newman Exit Code
        run: |
          if [ $(docker inspect newman --format='{{.State.ExitCode}}') -ne 0 ] 
          then
            echo "Newman failed."
            exit 1
          fi
      - name: Check if Newman is in endless loop
        run: |
          if [ $(docker ps | grep newman | wc -l) -ne 0 ]
          then
            echo "Newman still running."
            exit 1
          fi
