name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Build and Test with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build

  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Newman Test Run
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          collectionID: 10954437-8cb0d465-dff6-4319-a607-caad24998335
          environmentID: 98798-a974f882-8ecg0-4c80-9901-a583778393987a
      - run: npm install -g newman
      - run: newman run "https://api.getpostman.com/collections/${{collectionID}}?apikey=${{ secrets.POSTMANAPIKEY }}" --environment "https://api.getpostman.com/environments/${{ environmentID }}?apikey=${{ secrets.POSTMANAPIKEY }}"
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Newman
      uses: ./
      id: run-api-tests
      with:
        collection: "./NewmanCli/Newman_collection.json"
        reporters: cli
    
    - name: Export Summary from Outputs
      run: |
        echo ${{ steps.run-api-tests.outputs.summary }}
